ipc = off
splash = false
wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/paper/harbor-sunset.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/paper/harbor-sunset.jpg
    fit_mode = cover
}

