ipc = off
splash = false
wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/wall2.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/wall2.jpeg
    fit_mode = cover
}

